language: php

php:
  - 7.0
  - 5.6
  - 5.3
  - 5.4
  - 5.5
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls --verbose
